#!/bin/bash

set -euxo pipefail

SCRIPT=$(readlink -f "${BASH_SOURCE[0]}")
SCRIPTDIR=$(dirname ${SCRIPT})
COMBODIR=$(dirname $(realpath --no-symlinks ${BASH_SOURCE[0]}))
if [[ "${SCRIPTDIR}" == "${COMBODIR}" ]]; then
COMBODIR=$(realpath --no-symlinks "${SCRIPTDIR}/../..")
fi

LAYERS=""

setup_profile() {
(
PROFILE=$1
PROFILEFILE=${SCRIPTDIR}/$(basename ${PROFILE} .conf).conf
PROFILENAME=$(basename ${PROFILEFILE} .conf)
PROFILEDIR="${COMBODIR}-build-${PROFILENAME}"
DISTRO="poky"
DEFAULT_IMAGE="core-image-minimal"

source ${PROFILEFILE}

set +u
source ${COMBODIR}/src/poky/oe-init-build-env ${PROFILEDIR}
set -u

cat >bbwrapper.conf <<EOF
# this file is generated by ${SCRIPT}, changes to this file will be overwritten

${CONFIG:-}

MACHINE="${MACHINE}"
DISTRO="${DISTRO}"
EOF

cat >yoctoenv.sh <<EOF
#!/bin/bash

# this file is generated by ${SCRIPT}, changes to this file will be overwritten

export MACHINE=${MACHINE}
export DISTRO=${DISTRO}
source ${COMBODIR}/src/poky/oe-init-build-env ${PROFILEDIR}
cd \$OLDPWD
set -x
exec "\$@"
EOF
chmod +x yoctoenv.sh

cat >bbwrapper.sh <<EOF
#!/bin/bash

# this file is generated by setup_profile.sh, changes to this file will be overwritten

source ${COMBODIR}/src/poky/oe-init-build-env ${PROFILEDIR} >/dev/null
BITBAKE_CMD="bitbake -r ${PWD}/bbwrapper.conf"
cd \$OLDPWD

if [ "\$#" -eq 0 ]; then
set -x
\${BITBAKE_CMD} ${DEFAULT_IMAGE}
else
set -x
\${BITBAKE_CMD} "\$@"
fi
EOF
chmod +x bbwrapper.sh


if [[ ! -e "downloads" ]]; then
ln -sf $HOME/.yoctocache/downloads
fi
if [[ ! -e "sstate-cache" ]]; then
ln -sf $HOME/.yoctocache/sstate-cache
fi

if [[ "$LAYERS" ]]; then
bitbake-layers add-layer --force $(cd ${COMBODIR}/src; echo $LAYERS | xargs readlink -f)
fi

)
}

setup_profile test-genericx86-64.conf
